name: 'Universal Version Bumper'
description: 'Bump version in any JSON or TOML file with this simple Action'
author: 'Dervex'

branding:
  icon: 'chevrons-up'
  color: 'blue'

inputs:
  path:
    description: 'Path to the JSON or TOML file you want to bump'
    required: true
  version:
    description: 'The version to bump to, defaults to the tag name'
    required: false
  format:
    description: 'The format of the file you want to bump, defaults to the file extension'
    required: false

outputs:
  new_version:
    description: 'The new file version'
  old_version:
    description: 'The previous file version'

runs:
  using: node20
  main: dist/index.js
